### ISSUE TITLE
migrate ontology to Unicode

### ISSUE THREAD

**Issue by grexe** [peterstefanov/Ontology#1]
I am surprised to see the charset of the [emojiOntoloy.owl](https://github.com/peterstefanov/Ontology/blob/master/EmojiOntology.owl) is set to "windows-1252" which contradicts semantic web standards in a way and also emoji standards, as they are fully and officially supported by Unicode.
Please migrate the file to windows-1252, I immediately got character issues on my Linux system when downloading with Firefox...

**Comment by peterstefanov** [comment]
Hi Gregor,

Thanks for logging in this issue and your feedbacks are very much appreciated. I agreed with your comments in general ,however, this file is generated by the code and I believe at that time I was running in Windows environment so it wasn't an issue for me.

Your point is valid:
I already have in the pom.xml - Source encoding set to UTF8 (project.build.sourceEncoding to UTF-8 in maven properties)
You can try running the code from command line and pass these arguments -Dfile.encoding=utf8 and -Dsun.jnu.encoding=utf8 

this should do the job

**Comment by peterstefanov** [comment]
Amended in README the instructions how to run the code
